### ISSUE TITLE
Possibly incorrect status code 401

### ISSUE THREAD

**Issue by mpaddle** [wildbit/postmark-php#11]
I'm currently integrating this package into our systems and I'm looking for a way to differentiate between requests that should be retried and requests that should not be retried. Looking through the code for clues I found the following line: https://github.com/wildbit/postmark-php/blob/master/src/Postmark/PostmarkClientBase.php#L118
Is it meant to return `401` as an HTTP status code, or should it be the actual status code `422`?

**Comment by atheken** [comment]
@mpaddle You're right, this was a mistake when I authored the file. Good catch!

**Comment by mpaddle** [comment]
Thanks for the quick response and fix, @atheken
