### ISSUE TITLE
Installation on Laravel 5.1 failed 

### ISSUE THREAD

**Issue by saqueib** [wildbit/postmark-php#12]
I am getting below error by running `composer require wildbit/postmark-php`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install wildbit/postmark-php 1.3.2
    - Conclusion: don't install wildbit/postmark-php 1.3.1
    - Conclusion: remove guzzlehttp/guzzle 6.1.0
    - Installation request for wildbit/postmark-php ^1.3 -> satisfiable by wildbit/postmark-php[1.3.0, 1.3.1, 1.3.2].
    - Conclusion: don't install guzzlehttp/guzzle 6.1.0
    - wildbit/postmark-php 1.3.0 requires guzzlehttp/guzzle ~5.1 -> satisfiable by guzzlehttp/guzzle[5.1.0, 5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.0].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.0].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.0].
    - Installation request for guzzlehttp/guzzle == 6.1.0.0 -> satisfiable by guzzlehttp/guzzle[6.1.0].


Installation failed, reverting ./composer.json to its original content.
```

I need to send email with template (`$client->sendEmailWithTemplate()`), I dont know is it supported in Laravel provider of this package https://github.com/wildbit/laravel-postmark-provider

**Comment by atheken** [comment]
Hi @saqueib - Laravel's mail system already handles the job of sending "templated" mail, so if you're just trying to send mail through the built-in Mail processing, I think that's your best bet. 

However, we can look into compatibility of having both the postmark-php lib and the adapter in the same Laravel project, if you think you need to send some email using the Laravel Mail functionality, and then also send email through Postmark using our Templating system.

**Comment by saqueib** [comment]
@atheken I dont want to use the laravel `view` as template, currently I am not able install `composer require wildbit/postmark-php`, I want to go with Postmark template which is pretty good

**Comment by saqueib** [comment]
Hi @atheken, I have tried using Guzzle to make the request from Laravel but I am getting `422` with message `Unprocessable Entity`, below is my code please help whats going wrong 

```php
public function send($to, $from, $subject = null, $data = [], $templateId = null)
    {
        $postData = [
          "From" => $from,
          "To" => $to,
          "TemplateId" => $templateId,
          "TemplateModel" => $data
        ];

        // Create a Guzzle Client
        $client = new Client($this->baseApiUrl);

        try{
            // Fire the request and get the response
            $response = $client->post('email/withTemplate', [
                'X-Postmark-Server-Token' => env("MAILER_API_TOKEN"),
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
            ], $postData)->send();

            return $response->isSuccessful();
            
        }catch (RequestException $e) {
            echo $e->getRequest();
            echo $e->getMessage();
        }
        
        return false;
    }
```

If you can fix the installation issue will be great.

**Comment by atheken** [comment]
@saqueib Thanks for posting this. I'm also really glad to here you like Postmark Templates. I think that you should be able to require the following in your composer.json file and then run `composer update`

```json
"require": {
        ......<other dependencies>......
        "wildbit/postmark-php": "dev-updated-guzzle"
},
```

This uses guzzle 6.0 or newer.

**Comment by saqueib** [comment]
Thanks @atheken, now Its installed, and successfully sent a test mail :smile:

**Comment by djaiss** [comment]
Thanks for this thread. I was trying to make it work too, had the exact same error with Laravel 5.1.

You should update the readme to indicate that the current production version of your package is not compatible with Laravel 5.1.

We really like Postmark around here and we don't want to use Mandrill :-)
