### ISSUE TITLE
Where is the autoload.php?

### ISSUE THREAD

**Issue by levybee** [wildbit/postmark-php#21]
I see 'require_once('./vendor/autoload.php');' but there is no 'vendor/autoload.php' in 'postmark-php-master' that I have downloaded.

**Comment by reinink** [comment]
Just jumping in here to help out, `require_once('./vendor/autoload.php');` is created by [Composer](https://getcomposer.org), a dependency manager for PHP. If you choose to download the source code manually, you'll have to setup the autoloading yourself (not recommended).

If you're new to PHP or Composer, I highly recommend learning how to use this tool, *really* useful.

**Comment by atheken** [comment]
Thanks @reinink!

@levybee If you're not comfortable using Composer yet, we also periodically zip up releases and post them on our "Releases" page for this repo, here's the bundle from 2.1.0: https://github.com/wildbit/postmark-php/releases/download/2.1.0/bundle_2.1.0.zip

**Comment by levybee** [comment]
Thanks @reinink @atheken ,  I  used an old version of postmark instead, I think I will get my hands dirty with Composer sometime soon.

**Comment by reinink** [comment]
@levybee Nice, you won't regret it, I promise! 👍
