### ISSUE TITLE
undefined function GuzzleHttp\Handler\curl_reset()

### ISSUE THREAD

**Issue by mayurpande** [wildbit/postmark-php#26]
Hi,

I just installed this repo in my code and followed it exactly however was getting the error;

"undefined function GuzzleHttp\Handler\curl_reset()"

After googling around I read that I needed to change my php version to >=5.5 so I have done that.

But then the error disappears and then I get an error saying;

"Whoops, looks like something went wrong."

That is all I am getting. I am using godaddy hosting if that has anything to do with it. 

It was working fine locally on my machine.

![wildbit](https://cloud.githubusercontent.com/assets/6522456/16540353/cf4fb9be-4059-11e6-98e6-09cb29ef53a8.png)

**Comment by atheken** [comment]
Hi @mayurpande, It's hard to know for sure, this probably means that GoDaddy is not including the "libcurl" PHP extension. If you do a `<? phpinfo(); ?>` from a page on the server, there should be a curl module installed, with output (similar) to the following:

```
curl

cURL support => enabled
cURL Information => 7.43.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => No
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-apple-darwin15.0
SSL Version => SecureTransport
ZLib Version => 1.2.5
```

Just in case you didn't do this, `composer` creates a folder called `vendor` on your local machine. You should upload the `vendor` folder, along with your code when you publish your files to the GoDaddy server.

**Comment by mayurpande** [comment]
Hi,

Thanks for the reply. Sorry I should.have mentioned I managed to resolve it.

**Comment by atheken** [comment]
@mayurpande Just in case someone else stumbles upon this later, do you mind posting what you did to fix it?

**Comment by mayurpande** [comment]
Sure will do but I think it was something trivial like I forgot to change
the password and username for my mysql connection!

Kind regards,

Mayur

**Comment by atheken** [comment]
@mayurpande Thanks for posting the solution. You never know if someone will stumble upon this issue and wonder what to do to solve it. :-)
