### ISSUE TITLE
PostmarkException: Received valid, but incompatible JSON input

### ISSUE THREAD

**Issue by niteshsisodia** [wildbit/postmark-php#33]
I'm getting an exception while sending email using Postmark PHP API.

Here are the logs for the same :
Postmark\Models\PostmarkException: Received valid, but incompatible JSON input. in /app/vendor/wildbit/postmark-php/src/Postmark/PostmarkClientBase.php:165 
Stack trace: 
#0 /app/vendor/wildbit/postmark-Postmark\PostmarkClientBase->processRestRequest('POST', '/email', Array)

**Comment by atheken** [comment]
Hi.

Normally, this means that there's some sort of issue with the data provided
to our API (we defer practically all of the validation to the API to avoid
problems when rolling out validation updates).

If you can contact support (http://support.postmarkapp.com/), with a
snippet of the code you're using to send, we can try to help identify what
the specific issue is.

//Andrew

**Comment by czmole** [comment]
Hi,

I am sure this has been solved for @niteshsisodia but if someone lands here from search results, thought to mention that I got this when not using the right order of the parameters, basically I skipped some of them by mistake and resulted in the same error. 

Regards,
Cata

**Comment by subdesign** [comment]
My error was I used an array for multiple bcc addresses, but Postmark needs a comma separated list for that. Bingo :)
Thanks

**Comment by dwjohnston** [comment]
The issue I had was the the TemplateId a number, defined at the top right corner of the templates - not the name the template.

**Comment by karlwilbur** [comment]
I just encountered this error by passing the wrong datatypes to [`PostmarkClient::sendEmail()`](https://github.com/wildbit/postmark-php/blob/master/src/Postmark/PostmarkClient.php) (empty arrays instead of `NULL`, for example). My code was "working" on my end, but I was passing in wrong values.
