### ISSUE TITLE
How can i get my server token.

### ISSUE THREAD

**Issue by slince** [wildbit/postmark-php#34]
I find my token on [https://account.postmarkapp.com/account/edit](https://account.postmarkapp.com/account/edit)

however it similar wrong.
I got a guzzle request exception
```
Error: exception 'Postmark\Models\PostmarkException' with message 'Unauthorized: Missing or incorrect API token in header. Please verify that you used the correct token when you constructed your client.' in C:\www\slshop\vendor\wildbit\postmark-php\src\Postmark\PostmarkClientBase.php:146
```

Such a low-level problem

Looking forward to your reply

**Comment by slince** [comment]
![image](https://cloud.githubusercontent.com/assets/3785826/24033223/d1e4d860-0b26-11e7-91d7-3d1b59a92182.png)

i have create a record for dkim; however It is still not available

**Comment by atheken** [comment]
Hi @slince - It looks like for your first issue, you're using the **Account token**, and you need to use a **Server token** - this can be done by creating/navigating to a new Server in the Postmark UI, and then copying the credential from there.

With respect to the DKIM Verification, I can't really help without knowing the domain. Please contact  support and we can get a case open to look into why it's not verified yet. http://support.postmarkapp.com/

**Comment by slince** [comment]
@atheken  tks, it's seems ok now!
