### ISSUE TITLE
Tests make live requests?

### ISSUE THREAD

**Issue by webignition** [wildbit/postmark-php#46]
Running the phpunit tests seems to (attempt to) make live, actual requests over the Internet to ... a postmark test server I guess?

Just wondering if this is entirely necessary. For the purpose of this library, we should be able to assume that Postmark itself its working and just mock the HTTP interaction. Guzzle's mocking middleware is awesome for this.

**Comment by atheken** [comment]
Yeah, that's a "feature, not a bug." It ensures tests catch any typos or other incompatibilities with the Postmark API.

Under normal circumstances, I would want to mock an I/O, but since this library is the integration point between the two, the tests need to actually run against our live API.

**Comment by webignition** [comment]
:+1: fair enough
