### ISSUE TITLE
$trackOpens defaults to TRUE, but documentation says it defaults to FALSE

### ISSUE THREAD

**Issue by esn-int** [wildbit/postmark-php#52]
[Here ](https://postmarkapp.com/developer/user-guide/tracking-opens/tracking-opens-per-email)it says that postmark shouldn't track emails being open by default. Nevertheless,  the methods to send an email in the PostmarkClient class have the parameter $trackOpens default to TRUE.

Am I looking at the right documentation?

**Comment by atheken** [comment]
Our HTTP API does default to false. However, the PHP client explicitly enables Open Tracking, as we believed this would be the preferred setting for people when using the library. I can see how that would be a bit confusing, but changing the default to `false` to match the API default would be a breaking change.

**Comment by ctessmer** [comment]
I was running into this same issue and spoke with Shelley at Postmark about it. Sounds like they'll have a fix soon!

**Comment by vladsandu** [comment]
@ctessmer this was fixed by #72 and available in the 3.0.0 release.

**Comment by ctessmer** [comment]
Thank you so much @vladsandu!!
