### ISSUE TITLE
Support for TemplateAlias when sending email

### ISSUE THREAD

**Issue by strongn** [wildbit/postmark-php#56]
Hi - are there any plans for supporting TemplateAlias when sending emails using sendEmailWithTemplate()?

Regards,
Neil

**Comment by barrycarton** [comment]
Hello.
Agreed there is a branch that should be retrocompatible waiting for a merge. I need it.

**Comment by 99linesofcode** [comment]
As far as I can tell this is already part of the 2.7.0 tag. The only thing that appears to be lacking is a synchronized/pushed version on packagist.org

**Comment by atheken** [comment]
@99linesofcode, sorry about that, I expected packagist to pick the tag up, but it also required creating a github release. 😅- 2.7.0 Should be all set now.

**Comment by 99linesofcode** [comment]
Appreciate the quick response @atheken. Thanks.
