### ISSUE TITLE
Batch function improvment

### ISSUE THREAD

**Issue by jkrassman** [wildbit/postmark-php#59]
Why is there not an option to pass a custom parameter when sending batches? That parameter should then be sent back in the response so that it is easy to update a database when sending hundreds of messages.

As I see it as it is now, I have to use a separate array to keep track of my messages and then compare it to the response since the order is the same. Not that nice solution and rather uggly.

Any ideas?

**Comment by atheken** [comment]
Not exactly sure what you mean by "custom parameter", can you clarify what you mean by this?

**Comment by jkrassman** [comment]
When I am sending a batch I want to send my ID from my recordset in the database in a custom parameter in the array. Then I want the responseobject to contain my custom parameter so that I easily can update each record in the db. As it is now, the recordset is closed and I am only returning a response and it is hard to update the right recordset in the db.

**Comment by jkrassman** [comment]
Hard to explain but I was thinking of something like this:

```
$message2 = ['To' => "someone@someplace.com",
             'Cc' => "someoneelse@someplace.com",
             'Subject' => "Message 1",
             'HtmlBody' =>"<b>HELLO!</b>",
             'From' => "you@yourdomain.com",
             'Param1' => '12345'];
```

And when I cycle through the response object, I can easily see what messages all the status are for.

```
foreach($responses as $key=>$response){

      var_dump($response);

      echo "<br>" . $response['Param1'];
      echo "<br>" . $response['MessageID'];

  }
```

**Comment by atheken** [comment]
Ok. This is sometimes referred to as a “surrogate key,” it’s definitely useful and something we’ve considered adding, but would be a change to the overall Postmark API and not this specific client library.

Based on how you’re describing using it, it seems you’d be generating this as a sequence from the source messages, anyway, and the Postmark batch endpoints guarantee the response order is the same as the submission order, so it seems like you could correlate based on the index of the source array and the result array, unless I’m missing something.

**Comment by jkrassman** [comment]
Yes, the API needs changes as well and not only the client library.

I solved it by adding an array with my identifers - but it looks a little uggly, but it works.

"Surrogate key" -  never heard of :)

Regards, Joakim

**Comment by atheken** [comment]
For sure, it's definitely something we want to improve in a future version of the API. Thanks for suggesting it, and I'm glad you were able to get something working with the existing library/api endpoint.
