### ISSUE TITLE
Support for PHP 5.3

### ISSUE THREAD

**Issue by jxmallett** [wildbit/postmark-php#7]
As it stands, I think the only reason this doesn't support PHP 5.3 is because short array notation is used. Would you be interested in adding support for PHP 5.3 if I made a pull request with the changes?

I know 5.3 is getting pretty old, but the support would be nice to have.

**Comment by atheken** [comment]
@jxmallett Sure! If you'd like to do the conversion, we'll review it and integrate it. Thanks for the offer.

**Comment by jxmallett** [comment]
Done and done :) https://github.com/wildbit/postmark-php/pull/9

**Comment by atheken** [comment]
I see that, and it's merged. Thanks again.
