### ISSUE TITLE
MessageId should be string not int

### ISSUE THREAD

**Issue by baci266** [wildbit/postmark-php#77]
According to official documentation https://postmarkapp.com/developer/api/messages-api, messageId should be string.
In PostmarkClient there is integer: `@param integer $id The ID of the Message for which we want details.`

**Comment by vladsandu** [comment]
@baci266 thank you for submitting this issue. You are correct, that should be documented as a `string` argument.

I will make sure to include this update in the next release.

**Comment by vladsandu** [comment]
Thank you again for bringing this up! This was corrected in [release 4.0.1](https://github.com/wildbit/postmark-php/releases/tag/4.0.1).
