### ISSUE TITLE
PostmarkException Code 406: Parsing Message to get inactive emails

### ISSUE THREAD

**Issue by raygig** [wildbit/postmark-php#86]
I am receiving a PHP exception: PostmarkException 406 from the API. In that exception there is a message which indicates what emails are inactive. Currently I have to parse the message to get the emails so I can do some processing on my end. Would it be possible to throw a new exception called PostmarkInactiveRecipientException that has a property called $recipients which stores the array of inactive emails.

The current exception message:

You tried to send to a recipient that has been marked as inactive. Found inactive addresses: bademail1@baddomain00000.com, bademail2@baddomain00000.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.

**Comment by ewood-ac** [comment]
Thanks for this suggestion. We will keep it in mind as we move forward.
